package com.mvvm.kien2111.mvvmapplication;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.support.test.InstrumentationRegistry;
import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;

import com.mvvm.kien2111.mvvmapplication.ui.universal.UniversalActivity;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

/**
 * Instrumented test, which will execute on an Android device.
 *
 * @see <a href="http://d.android.com/tools/testing">Testing documentation</a>
 */
@RunWith(AndroidJUnit4.class)
public class ExampleInstrumentedTest {

    //assign these test rule to the test
    @Rule
    public ActivityTestRule testRule = new ActivityTestRule(UniversalActivity.class,false);


    @Test
    public void testDynamicLink() {

        //Dynamic link url
        String url = "http://fastjob.com/welcome";

        //create intent
        Intent intent = new Intent (Intent.ACTION_VIEW);
        intent.setData (Uri.parse(url));

        //launch activity with the url as intent. Should work exactly as open from the email generated by Firebase invite function.
        testRule.launchActivity(intent);
    }
}
